### ISSUE TITLE
FRONT END - show available in quantity in the product but when viewing in detail, product sizes aren't showing up

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#10]
The Cowl Neck Draped Maxi show available quantity of product on category page but when viewing in product page, the product is all out of stock. This is applied to all product, please ask your developer to correct it. 

Please see below for detail 
![img_3710](https://cloud.githubusercontent.com/assets/9522928/9242823/3c712278-41cb-11e5-9075-87382d5c5446.PNG)

![img_3711](https://cloud.githubusercontent.com/assets/9522928/9242827/42f9d89c-41cb-11e5-9312-11a086e56e22.PNG)

**Comment by supremesupports** [comment]
Hi, 

This issue has been fixed. Can you please check and let us know?

Thanks.

**Comment by Stellyclothing** [comment]
Hi

Thanks. Working now

Thanks
Phong

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
It's happening again tonight , please have a look 
![screen shot 2015-08-16 at 11 41 30 pm](https://cloud.githubusercontent.com/assets/9522928/9293464/913feea0-446f-11e5-8359-048a3166a947.png)

![screen shot 2015-08-16 at 11 42 11 pm](https://cloud.githubusercontent.com/assets/9522928/9293466/a2058916-446f-11e5-98ae-6d5bd7b336b6.png)

**Comment by wildfirecreative** [comment]
This appears to only be happening on the test products - @supremesupports  please double check the issue though

**Comment by supremesupports** [comment]
We are working on this issue

**Comment by Stellyclothing** [comment]
Has this been fixed or are we still waiting ? 

Thank you

**Comment by supremesupports** [comment]
This issue is fixed

**Comment by Stellyclothing** [comment]
Hi

I just test and it is updated in product page but not updated in category page when I manually increase or decrease under Catalog/Products/Quantities. Please check for reference item is 123456 for more details.

Thanks
Phong

**Comment by Stellyclothing** [comment]
Hi supremesupports,

Thank you. It is working now.

Thanks
Phong
