### ISSUE TITLE
Shipping issues

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#11]
Hi
1. The wrong message when order is $59.95 and customer is already having free shipping. This message should appear on order under $50.
![wrongmessage2](https://cloud.githubusercontent.com/assets/9522928/9249003/48ecdeb4-4204-11e5-87de-41890abbf100.PNG)
2. When order is under $50, shipping is $8.95 for Australia, News Zealand shipping is $15 when order is under $100 and the rest of the world is $25 when order is under $150.
![wrongmessage](https://cloud.githubusercontent.com/assets/9522928/9249060/d2f15248-4204-11e5-8aa8-2e4915df8c29.PNG)

Thanks
Phong

**Comment by supremesupports** [comment]
We are checking this issue.

**Comment by supremesupports** [comment]
Hi Phong, 
First issue is done. We are checking second one.

Thanks!

**Comment by Stellyclothing** [comment]
Hi Supremesupports

Thanks. Looking forward to hearing good news from your team. 

Thanks
Phong

**Comment by Stellyclothing** [comment]
@supremesupports hows the second one going ? 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

This issue is solved. Shipping has been configured according to this:
Australia - less than $50 - Charge $8.95
New Zealand - less than $100 - Charge $15
Rest of the countries - less than $150 - Charge $25

![shipping range](https://cloud.githubusercontent.com/assets/12905649/9427342/89809be4-499a-11e5-9468-11a128487dbf.PNG)



Free shipping: 
For Australia, when cart price is $50 or above
For New Zealand,  when cart price is $100 or above
For Rest of the countries, when cart price is $150 or above

Please have a look & let us know if it's working.

Thanks.

**Comment by Stellyclothing** [comment]
Hi THIS IS ALL WRONG 
@wildfirecreative  @supremesupports 
SOMEONE NEEDS TO FIX THIS QUICK AND TELL ME WHErE I CAN MANUALLY GO ??
THIS IS WHAT WE ARE HAVING NOW ON OUR CURRENT WEBSITE 

  
![screen shot 2015-08-23 at 8 25 29 pm](https://cloud.githubusercontent.com/assets/9522928/9427846/8f4b2a54-4980-11e5-87e7-8b66aa2ea935.png)

**Comment by Stellyclothing** [comment]
Australia : 0-to $49.95 is $8.95 , Over is Free Shipping
NZ : 0-t0 99.99 is $20 , Over is Free Shipping 
North America : 0 - to $149.99 is $25 , Over is Free Shipping 
The rest of the world : $25 flat rate all orders

**Comment by supremesupports** [comment]
Hi Josh,
This shipping has been configured according to Phong's thread (please check first thread of this post). Please let us know if we need to change it other way. We are getting confused.

You can update shipping range from here: Back-end >> Shipping >> Carriers. Then select Australia Post (There are two actually, please select the enabled one with the ID: 58). You can update range from here.

I've removed 'Free shipping' for  'rest of the world'.
Thanks!

**Comment by Stellyclothing** [comment]
HI Josh,

Shipping is working now. We can manually update from shipping/carriers/Australia Post and select edit to update.

Thanks
Phong
