### ISSUE TITLE
Order History issues

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#12]
Hi

When I try to open order details from order history to update message but I can't open it. Also, the invoice is not generating for this order as well
![invoice not generate](https://cloud.githubusercontent.com/assets/9522928/9249092/28dd6426-4205-11e5-98e0-df10fe02ce51.PNG)

Thanks
Phong

**Comment by supremesupports** [comment]
Hi,
This part is done. Please check.

Thanks!

**Comment by Stellyclothing** [comment]
Hi

Thanks. It works now.

Thanks
Phong

**Comment by Stellyclothing** [comment]
Hi Supremesupport,

Just found that the order history is working fine on safari, Google Chrome, Mozilla Firefox. However, for some reason, it is not working properly on IE. Please see reference below for details.

Thanks
Phong

**Comment by Stellyclothing** [comment]
![Uploading order history.PNG…]()
![Uploading order history2.PNG…]()

**Comment by Stellyclothing** [comment]
@supremesupports @wildfirecreative 
Is it still occurring on IE web browser ? or is it fixed ?

Thank You 
Josh

**Comment by supremesupports** [comment]
Hi,
This issue has been fixed.
Tested on both IE11 & Microsoft Edge.

Thanks.

**Comment by Stellyclothing** [comment]
Hi,

It is working now

Thanks
Phong
