### ISSUE TITLE
Product Image issue

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#13]
Hi,

This is the product image from the test site which show now gap in between the zoom image and the small image 
![product1 1](https://cloud.githubusercontent.com/assets/9522928/9249136/af583364-4205-11e5-84e1-c021f90395b2.PNG)

This product image is from the live site which show the gap in between the zoom image and the small image 
![product1](https://cloud.githubusercontent.com/assets/9522928/9249170/e8715162-4205-11e5-914e-a537c9d4f06b.PNG)

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,
Products additional images are okay now.

Thanks.

**Comment by Stellyclothing** [comment]
Okay its working now
