### ISSUE TITLE
Front END- Out of stock product allows to add to cart - then different size shows up

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#14]
Hi ,
I tried to add a product thats is out of stock to my cart ( Size 6)
It allows me to add to the cart . when i go to the checkout , it has added size 8 instead 6 

It shouldn't allow me to add anything to my cart at all if a product is out of stock ,instead a message underneath the out of stock size - asking for email to notify when we restock .

![screen shot 2015-08-16 at 11 32 38 pm](https://cloud.githubusercontent.com/assets/9522928/9293434/790e97e2-446e-11e5-97ed-def24ff5e272.png)
![screen shot 2015-08-16 at 11 34 32 pm](https://cloud.githubusercontent.com/assets/9522928/9293436/88dc8cec-446e-11e5-8e58-8a140f294f83.png)

**Comment by wildfirecreative** [comment]
I just tested this and did not experience the same issue (functioned same as live site) - perhaps the cache needed to be reset or this has been fixed since.

**Comment by supremesupports** [comment]
This issue was solved in the latest version. You may tested in the previous version

**Comment by Stellyclothing** [comment]
yes its fine now
