### ISSUE TITLE
Front End - Selecting Add to Cart , takes me straight to the check out & many others

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#15]
Hi ,
In the product page 
When i select an image, it opens another page with that image
When i select the available size & add to cart, it takes me to the checkout 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi,
Product page is working exactly the same way like live (http://stelly.com.au/) site. May be you did your checking during our development time so you saw something different?
Can you please check back and let us know?

Thanks!

**Comment by Stellyclothing** [comment]
Hi

I checked and instead of adding each item to cart each time as normal, whenever I seleact a size, then click add to cart, it takes directly to check out page. 

Thanks 
Phong

**Comment by wildfirecreative** [comment]
I just tested this with a few products and did not experience the same issue. When I add the product to 'BAG' it adds to the cart, but does not take me to checkout.

**Comment by supremesupports** [comment]
Please re-check this issue and if you face it again, let us know the browser name you are using.

**Comment by Stellyclothing** [comment]
it does not anymore
