### ISSUE TITLE
Product combination issues

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#16]
Hi

I try to create a product and it is working ok. When it comes to products combination, here are the issues

1. The quantities of product on category page are not matched with product page.
2. Under product combination, I can't update inventory and I try to update it under quantity, it shown only on product page but not on product category page. Therefore, there are no link in between combination & quantity when I try to update. However, on the existing prestashop, under product combination, it allows to update products  inventory.
Please see attachment for details

Thanks
Phong

Front category product shown incorrect inventory with product itself
![frontcombination](https://cloud.githubusercontent.com/assets/9522928/9296437/70dcb592-44d0-11e5-961c-70d4259e3ce8.PNG)
Product category
![productcombination](https://cloud.githubusercontent.com/assets/9522928/9296442/7a704948-44d0-11e5-86ec-6c53f1a093b1.PNG)

Product combination Prestashop 1.6 won't have function to update inventory
![combination1 6](https://cloud.githubusercontent.com/assets/9522928/9296457/af13bd6a-44d0-11e5-840c-39c89581a6c9.PNG)

Product combination Prestashop 1.4 have function to update inventory
![combination1 4](https://cloud.githubusercontent.com/assets/9522928/9296460/b42eb67e-44d0-11e5-91f8-449eb5287cfb.PNG)

Update product manually under quantity but only update on product itself
![quantiy](https://cloud.githubusercontent.com/assets/9522928/9296462/b9d0254a-44d0-11e5-8d2e-8317b458263b.PNG)

**Comment by Stellyclothing** [comment]
Hi Supremesupports,

The issues in regarding to product combination is whenever we update inventory manually under products/Quantities, it only update inventory in product page and not in category product page. It needs automatically updating both category product page and product page when we manually adjust inventories.

Thanks
Phong

**Comment by supremesupports** [comment]
We are working on this issue. Issue #16, #10, #5 are related to each other.

**Comment by Stellyclothing** [comment]
@wildfirecreative @supremesupports how is it going ? is it completed ? 

Thanks
josh

**Comment by Stellyclothing** [comment]
Hi @supremesupports @supremesupports  PHONG SAID this has not been fixed 
Please let us know when this can be done by,we have to go live ASAP 

Thanks
JOSH

**Comment by supremesupports** [comment]
This issue is fixed

**Comment by Stellyclothing** [comment]
Hi supremesupports

Thank you. It is working now.

Thanks
Phong
