### ISSUE TITLE
Inventory & shipping

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#17]
Hi @supremesupports @wildfirecreative 

Any ideals of when will your team complete these two issues?

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,
Shipping part is done. We are working on inventory part now.

Thanks!

**Comment by Stellyclothing** [comment]
Hi Supremesupports,

Thanks. Will the inventory part finish soon today? 

Thanks
Phong

**Comment by supremesupports** [comment]
Inventory part  is fixed too.

**Comment by Stellyclothing** [comment]
Hi Supremesupports,

Thank you. Finally it is fixed.

Thanks
Phong
