### ISSUE TITLE
Size in category is missing 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#18]
![screen shot 2015-08-22 at 4 18 13 pm](https://cloud.githubusercontent.com/assets/9522928/9422805/94671a40-48e8-11e5-9267-fad98bc1a87c.png)

HI its missing size 12 and 14 and other sizes ?

Thanks

**Comment by supremesupports** [comment]
Hi,
This is showing now.
![category-sorting](https://cloud.githubusercontent.com/assets/12905649/9427752/d46085f2-49ae-11e5-8756-3f6eaec6c9d0.PNG)

Thanks!

**Comment by Stellyclothing** [comment]
Okay thanks
