### ISSUE TITLE
Log in issue with Input Addresses for  Australia Account - No City  - With United States - No States is Allow - Enter Personal address twice 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#19]
_From @Stellyclothing on June 11, 2015 6:27_

![screen shot 2015-06-04 at 10 54 52 am 2](https://cloud.githubusercontent.com/assets/9522928/8101064/c8cd0d00-1056-11e5-93cc-9b8156290352.png)
Australia Pode charge code is : 3J55

I tried to register
It would let me register fine.
But then we had some issue with the address 

So when i tried to register my address , the country default was USA , it had the City( SUBURB)  Box for entering
I then Changed to Australia and the city section is gone

Below it would ask me to fill me my city 
But theres no where to put my city

_Copied from original issue: Stellyclothing/Stelly-New-Website#3_

**Comment by Stellyclothing** [comment]
Address problem number 2 

This problem is also happening with International 
But only when enter United States as a country - i'm unable to add the correct states in my account , i can only input Australia States .

This has something to do with Which postcode to put in first

**Comment by Stellyclothing** [comment]
_From @supremesupports on June 16, 2015 6:34_

City field is visible now if you are selecting Australia as country. Also, If you switch country between Australia & USA, States are also changing respectively.

**Comment by Stellyclothing** [comment]
hi 
IM trying to register as a new customer and still having issue with the city 
So as default for united states, i was able to input city 

But as changing to australia suburb/city is not there any more , please see attachment
![screen shot 2015-06-16 at 6 40 50 pm](https://cloud.githubusercontent.com/assets/9522928/8179049/402b35f8-1457-11e5-876c-70cf372a4022.png)
![screen shot 2015-06-16 at 6 40 01 pm](https://cloud.githubusercontent.com/assets/9522928/8179050/407daf86-1457-11e5-900e-30d75a80008b.png)

**Comment by Stellyclothing** [comment]
After i registered with an address 
I selected a product and go to the checkout
The system would ask for my address again 
This time city is there to input

But i shouldn't have to enter my address twice. 
Please have a look 
![screen shot 2015-06-16 at 6 45 41 pm](https://cloud.githubusercontent.com/assets/9522928/8179164/1ca144be-1458-11e5-9583-3196782d5b0c.png)

**Comment by Stellyclothing** [comment]
@wildfirecreative  hey luke, this has not yet been fixed completely

**Comment by Stellyclothing** [comment]
_From @wildfirecreative on June 22, 2015 1:45_

Supreme can you please review this again

**Comment by Stellyclothing** [comment]
THIS iS HAPPENING now on the staging site 
@wildfirecreative @supremesupports 

Please have a look

**Comment by supremesupports** [comment]
Hi,
We are working on this.

Thanks!

**Comment by supremesupports** [comment]
Hi,
This issue has been Fixed. You will notice the checkout steps has been changed too.

Explanation: We migrated the website from Prestashop 1.4 to 1.6 but the theme was not updated 100% according to Prestashop 1.6. Prestashop has changed the checkout steps in version 1.6 . You can check default 1.6 prestashop here: http://54.153.131.0/ps16/ . We had old checkout steps in theme but we do not have those in core Prestashop coding. That is why it was not working. 

 it is working after the checkout steps in the theme has been changed.
Thanks

**Comment by Stellyclothing** [comment]
Hi,

It is working now.

thanks
phong

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
IT WORKS 

So what happened is its no longer ask for the full address at checkout
Just your name , email  & register  , THEN LATER ON WHEN CHECK OUT IT WILL ASK FOR FULL ADDReSS ? 

BTW where does this goes ?
Receive special offers from our partners????
![screen shot 2015-08-25 at 12 23 38 pm](https://cloud.githubusercontent.com/assets/9522928/9457230/c063e550-4b23-11e5-8bf8-17c560ac5248.png)


Thanks 

Josh

**Comment by supremesupports** [comment]
Hi Josh,
This will no longer ask 'Address' at first place. If you are not logged in & you already have your product added on cart then address from will be appear after registration. Otherwise it'll ask for address during checkout.

Checkbox for newsletter & promotional offer is also available for current registration.

Thanks!

**Comment by Stellyclothing** [comment]
thank you 
Josh
