### ISSUE TITLE
Unable to upload Images - This is the message I'm getting

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#2]
![screen shot 2015-08-13 at 11 19 28 am](https://cloud.githubusercontent.com/assets/9522928/9240733/13b47c04-41ad-11e5-8cb6-d78b3a408718.png)

**Comment by supremesupports** [comment]
Hi,
Product image uploading is working fine although its a bit slow. We'll start working on server performance once we are done with prestashop related bugs.

Thanks!

**Comment by Stellyclothing** [comment]
the testing site is down ,we are unable to access @wildfirecreative @supremesupports

**Comment by supremesupports** [comment]
Site is accessible now: http://54.153.131.0/

**Comment by supremesupports** [comment]
Product image uploading is working fine and site speed is okay now

**Comment by Stellyclothing** [comment]
Hi 

it seems that the site is loading ok without turning cache on

Thanks
Phong

**Comment by Stellyclothing** [comment]
it works fine 

Thanks 
Josh
