### ISSUE TITLE
Conversion Tracking for Google Analytics & Adwords

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#20]
_From @Stellyclothing on June 12, 2015 4:25_

Hi , 
Google Conversion Tracking & Adwords are not properly tracking 

THanks 

_Copied from original issue: Stellyclothing/Stelly-New-Website#9_

**Comment by supremesupports** [comment]
Hi,
Google Conversion Tracking & Adwords has been added to staging site.

Thanks!

**Comment by Stellyclothing** [comment]
Hi @supremesupports if it has been added , does it mean the current tracking aren't working on my live website ?

**Comment by supremesupports** [comment]
Hi,
I should work on both sites.

Thanks!

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
I will go back and check this later when the site is live 

Thank You 
Josh

**Comment by Stellyclothing** [comment]
Hi @wildfirecreative @supremesupports 

Now the site is live
Can you guys let me know has the code been embedded on every page of the site for a proper tracking ?

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Google adservice & analytics code is embedded on every pages.

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
The I'm checking google anyaltics now 
But with adwords tracking is not working right 
I think you suppose to put it at the end of the checkout ???
I will call google tomorrow and find out why its not working right

Thank You
JOsh

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
 Created two new issues for each adwords & Analytics 
Sent an email to luke with all the info , if not you can also check on here 

im closing this one and move to the new one
