### ISSUE TITLE
Stelly Logo on each invoice

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#24]
Hi 

The invoice doesn't have on Stelly Invoice. Please below for details

Thanks
Phong

![stelly logo](https://cloud.githubusercontent.com/assets/9522928/9428194/84a3ca0a-49e6-11e5-8021-34d1bf6aad61.PNG)

**Comment by supremesupports** [comment]
This issue has been fixed.

**Comment by Stellyclothing** [comment]
Hey Thanks

**Comment by Stellyclothing** [comment]
this is happening again @wildfirecreative @supremesupports 

Phong

**Comment by supremesupports** [comment]
hi,
We disabled the image folder for some while for a testing and you checked this issue at that time. That is why the system was showing the default image. Please check now. 

Thanks

**Comment by Stellyclothing** [comment]
Okay thanks 
it works now 

josh
