### ISSUE TITLE
Warehouse location is not showing on ORDER , not Invoice 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#25]
Hi @wildfirecreative @supremesupports  

Please have a look and locate the location of our product in the orders 

Let me know if this can be done today ? if not we will wait until our site goes live on AWS 

Same order 132009

![screen shot 2015-08-24 at 10 53 02 am](https://cloud.githubusercontent.com/assets/9522928/9431126/6d952d78-4a4e-11e5-9b4a-d32e55f11797.png)
![screen shot 2015-08-24 at 10 52 47 am](https://cloud.githubusercontent.com/assets/9522928/9431127/6de2c1e6-4a4e-11e5-9fd3-5ed4a9bf7df8.png)
![screen shot 2015-08-24 at 10 54 55 am](https://cloud.githubusercontent.com/assets/9522928/9431128/6f147686-4a4e-11e5-9b08-16aa4b5fa0f4.png)

**Comment by supremesupports** [comment]
Hi, 
Location field is now available for Product, Order & Invoice:

![location-1](https://cloud.githubusercontent.com/assets/12905649/9432972/29da6072-4a4d-11e5-9919-eb43a4924b11.PNG)

![location-2](https://cloud.githubusercontent.com/assets/12905649/9432981/3e4e25de-4a4d-11e5-9c5d-6c71c87ba453.PNG)

![location-3](https://cloud.githubusercontent.com/assets/12905649/9432990/5a0686fe-4a4d-11e5-96f8-2540e04a013c.PNG)

Screenshot taken from Product ID: 18257, Order ID: 132128.

Thanks!

**Comment by Stellyclothing** [comment]
Thank You
