### ISSUE TITLE
Information and Customer service page does not exist

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#27]
Hi @wildfirecreative @supremesupports 

The information page of About us, careers, Terms & condition, Private policy
Sitemap, contact us, Online Return policy, shipping, size guide & FAQs does not exist. Please make these information available. Please see reference below for details

Thanks
Phong

![information](https://cloud.githubusercontent.com/assets/9522928/9458109/e958f3ec-4b2d-11e5-8b52-7addd4f6edf4.PNG)
![information2](https://cloud.githubusercontent.com/assets/9522928/9458110/e95f8888-4b2d-11e5-8f08-dea3ec78d5fa.PNG)

**Comment by supremesupports** [comment]
Hi,

Information and Customer service pages are showing now. Please have a look.

Thanks.

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Thank you. It is working now

Kindly regards
Phong
