### ISSUE TITLE
Shopping Cart update issue

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#28]
Hi @supremesupports @wildfirecreative 

Here is what I found when I test to decrease quantity of an item from cart. 

This is when I add item to cart shown on the check out
![cardinfo](https://cloud.githubusercontent.com/assets/9522928/9458225/361cb99c-4b2f-11e5-87a2-97c2c3391787.PNG)

Then, after I decrease item from cart, the cart is empty but still showing amount on cart.
![cardinfo2](https://cloud.githubusercontent.com/assets/9522928/9458229/500c4d86-4b2f-11e5-943c-b4759a5183fc.PNG)

Then I have to refresh the page again, and this time, it shown the empty cart.
![cardinfo3](https://cloud.githubusercontent.com/assets/9522928/9458244/7d7ebdbc-4b2f-11e5-9482-b5ed29673656.PNG)

The cart should shown empty cart information when there are none items in the cart. Please make sure that when none item from cart, it is needed to show shopping cart is empty to avoid confusing to customer. 

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,

This issue is no longer appearing as we moved to step-by-step checkout. 

Thanks.
