### ISSUE TITLE
Log In and Out issue

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#29]
Hi Supremesupport,

I am trying to log out but there are no "Log out" botton to click for signing out. Please see attachment for details.

Thanks
Phong

![login and out](https://cloud.githubusercontent.com/assets/9522928/9458676/9e9708f6-4b34-11e5-90fa-124a1ee86db0.PNG)

**Comment by supremesupports** [comment]
Hi,
we think you see this because you were browsing the website when we are doing some testing and upload was in process. please login from top right corner  of the page and your problem should be fixed .

Thanks

**Comment by Stellyclothing** [comment]
Hi,

I clear the caches and working now

Thanks
Phong
