### ISSUE TITLE
Front page Issue UpLOAD with BANNER

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#3]
Hi , 
If i try to upload multiple images on my front page banners
The images end up being the same 

![screen shot 2015-08-13 at 11 36 50 am](https://cloud.githubusercontent.com/assets/9522928/9240894/721ce8ba-41af-11e5-9964-e23079883ec8.png)
![screen shot 2015-08-13 at 11 37 35 am](https://cloud.githubusercontent.com/assets/9522928/9240895/726c7948-41af-11e5-85b1-8d7dec695e16.png)

**Comment by supremesupports** [comment]
Hello,
If you try to save multiple images at a time, then the first image will be saved for all slides.
To avoid this, you would need to select one image at a time the save it. It will works!

Thanks!

**Comment by Stellyclothing** [comment]
Hi @supremesupports its not suppose to be like that, I can save multiple images in the past . This is def not how it has functioned in the past !!! Can you please check for us. Could this be cache problems on the server ???? please check this for me also @wildfirecreative

**Comment by supremesupports** [comment]
we are checking how we can make it user friendly and same of live site.

**Comment by supremesupports** [comment]
Hi,
Slider module is working fine now. Please try to upload multiple image now.

PS: There is minor issue with slider's navigation button. I'll update that tomorrow.

Thanks

**Comment by supremesupports** [comment]
Hello,
This issue is fixed now.

After uploading the banner, if its don't appear in front-end then please clear the cache.
Go to Back-end >> Advanced Parameters >> Performance, then at the top-right section there is an option called 'Clear cache'. Click on it to clear your cache.

Thanks.

**Comment by Stellyclothing** [comment]
hi Just checked
It works , only after i clear the cache, 
But if i change again, i have to empty the cache one more time . is that normal ? 
@supremesupports @wildfirecreative

**Comment by supremesupports** [comment]
Yes, this is how its working on current site. If you clear cache after uploading images, then the impact will be visible immediately.

Thanks.
