### ISSUE TITLE
Can't view wishlist and delete it

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#31]
Hi @supremesupports @wildfirecreative 

When add item to wish and try to view it from the account, I can't view and delete if I don't need it. Please see reference for details  

Thanks
Phong

![wishlist](https://cloud.githubusercontent.com/assets/9522928/9462693/bf9768fe-4b5a-11e5-8062-68c74619d08c.PNG)

**Comment by Stellyclothing** [comment]
Hi

It is working on safari, Google Chrome, Mozilla Firefox but not on IE

Thanks
Phong

**Comment by supremesupports** [comment]
Hi,

Wishlist delete is working now. Please check.

Thanks.

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Wishlist is working now. However, the image is not appeared when viewing. Please see attachment for details

Thanks
Phong

![wishlist](https://cloud.githubusercontent.com/assets/9522928/9601660/7abbbef6-50e6-11e5-9cbd-1db8515e096d.PNG)

**Comment by supremesupports** [comment]
Hi,

Wishlist image is showing now.

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
it works now 

thanks
