### ISSUE TITLE
Problem of customer Message

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#33]
Hi @supremesupports @wildfirecreative 

When I log in the account and want to send an message but the message does not update on order

![customer message](https://cloud.githubusercontent.com/assets/9522928/9467518/a9657dda-4b7f-11e5-9aea-6ddcfb45917c.PNG)

**Comment by supremesupports** [comment]
Hi,

This problem has been solved. Please have a look now.

Thanks!

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Thank you. It is working now

Thanks
Phong
