### ISSUE TITLE
Send Message to friend

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#34]
Hi @supremesupports @wildfirecreative 

When I try to send message of an item to a friend, the image is not appeared and the link in the email is not working. Please attachment for details

Thanks
Phong

![send to friend](https://cloud.githubusercontent.com/assets/9522928/9491110/ffed9efc-4c2f-11e5-80eb-c4bf9c0e3ba9.PNG)
![send to friend2](https://cloud.githubusercontent.com/assets/9522928/9491111/007859d4-4c30-11e5-84da-49dd6422c7ca.PNG)

**Comment by supremesupports** [comment]
Hi,
This issue has been resolved.

Thanks.

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Thank you. It is working now but the pop up is small and look not right. When I check on other internet explore like google chrome, the pop up look better. Please see attachment for details

This is google chrome

![chrome](https://cloud.githubusercontent.com/assets/9522928/9494612/3ff89320-4c4a-11e5-864d-59c038d866d2.PNG)

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

It seems that the template to send email to friend doesn't show the image. Also, the template uses for IE look smaller than the template that is used for Google Chrome, Firefox or safari. Please see attachment for details.

Thanks
Phong

This template is from IE

![sendemail](https://cloud.githubusercontent.com/assets/9522928/9601796/431a5952-50e7-11e5-808e-3e43fd086992.PNG)

This template is from Chrome

![sendemailchrome](https://cloud.githubusercontent.com/assets/9522928/9601845/86e501aa-50e7-11e5-884d-89934fecc1e9.PNG)

Can Please make the template same as Chrome?

**Comment by Stellyclothing** [comment]
hey @supremesupports @wildfirecreative 
I just checked again on the new website
Its not work 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi, 

This issue has been fixed for IE as well.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports  it works now 

Thanks
Josh
