### ISSUE TITLE
Can't retrieve password for admin loin

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#35]
Hi @supremesupports @wildfirecreative 

I try to test to retrieve password for admin login but link to loss password not working. Please see attachment for details

Thanks
Phong

![adminlogin](https://cloud.githubusercontent.com/assets/9522928/9519120/5e1d0eac-4cff-11e5-8bdb-3a4f5d3a2e1e.PNG)

**Comment by supremesupports** [comment]
Hi,

This issue has been fixed.

Thanks.

**Comment by Stellyclothing** [comment]
Hi

Thank you.

Thanks
Phong
