### ISSUE TITLE
Sub Folder issue on NEW CMS - 404 ??

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#36]
Hi @wildfirecreative @supremesupports 
My concern is currently on our website as Luke & phong mentioned all data is saved under one folder 
But moving to the new CMS, it will create many sub-folders , which to my understanding to help the site load faster and easier to manage . Will it change my URL if we create muptiple sub folders , I could potentially lose ranking on Google if i have many 404 or 401 pages ? 

Thanks

**Comment by supremesupports** [comment]
Hi,

This is not about the website URLs. All URLs will remain same as it was. This is about saving the images. In live site, all the images are saved in single folder but in the new system images are saved in several sub-folders depending on the image id. This will not effect the website URLs or it is not related to Google SEO or 404 pages.

Thanks!

**Comment by Stellyclothing** [comment]
hey @supremesupports  thank you
