### ISSUE TITLE
BACKEND-Order Source is missing on the CMS

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#37]
Hi @wildfirecreative @supremesupports 
The source is not showing on the new prestashop on the order 
![screen shot 2015-09-01 at 8 11 50 pm](https://cloud.githubusercontent.com/assets/9522928/9601448/f18aa8c8-50e4-11e5-8a4e-2ed032bb248f.png)

Please update 

Thank You
josh

**Comment by supremesupports** [comment]
Hi Josh,

Seems like this was a core feature of Prestashop 1.4 which is now missing on Prestashop 1.6. We've tried it with fresh Prestashop 1.6 where we didn't found this feature as well.

Also, this is also missing in prestashop's demo site. Please it this here:

http://demo.prestashop.com/en/?view=back

Thanks.
