### ISSUE TITLE
BACK END- Can't upload files on new CMS 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#38]
Hi @wildfirecreative @supremesupports 
I try to go to preference and it doesn't let me upload file, it's just blank

![screen shot 2015-08-25 at 1 48 11 pm](https://cloud.githubusercontent.com/assets/9522928/9623062/2c86afd6-517f-11e5-8e93-089582ab0b38.png)

thank You 
Josh

**Comment by supremesupports** [comment]
Hi Josh,

File uploading + content saving is working now. Please have a look.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
i tested and it works fine
Will it work on all from now on ? 

Thanks 
josh

**Comment by Stellyclothing** [comment]
@supremesupports 
Its not working now 
I tried to upload two images on one page 
The images would doubling up instead od fall underneath each other

![screen shot 2015-09-07 at 12 22 15 am](https://cloud.githubusercontent.com/assets/9522928/9704780/c4a1c570-54f5-11e5-815a-1b003e4f9810.png)

![screen shot 2015-09-07 at 12 23 50 am](https://cloud.githubusercontent.com/assets/9522928/9704788/d430bbfe-54f5-11e5-88e4-c5a86f1fd56d.png)

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi Josh,

We've tried several ways to upload images alongside text & seems like its working well. Here are back-end screenshots:

![1](https://cloud.githubusercontent.com/assets/12905649/9709701/2096ca36-5552-11e5-8eea-83752d26d17f.jpg)

![2](https://cloud.githubusercontent.com/assets/12905649/9709702/29f1cfe0-5552-11e5-9b2b-f6ab1d023c36.jpg)

![3](https://cloud.githubusercontent.com/assets/12905649/9709705/3167e02a-5552-11e5-959e-87b50e89ca35.jpg)

Also, please have look in front-end of this CMS page here: http://54.153.218.42/content/26-test


Thanks.

**Comment by supremesupports** [comment]
Hi Josh,

We hope you are not having any issue regarding with CMS pages. We are closing it.

Thanks.
