### ISSUE TITLE
Unable to use Voucher code on Stelly Site

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#4]
Unable to use Voucher code on Stelly Testing Site - Created Successfully 

Hi , I was unable to use Stelly code on the testing site and it does not appear on my checkout , even i allowed it to appear on my checkout . 

I was also successfully created a voucher but it wouldn't let me use on the testing site 

![Uploading Screen Shot 2015-08-13 at 12.27.17 pm.png…]()

**Comment by supremesupports** [comment]
We've installed Gift voucher module & configured it as like Live site but we are unable to check whether its working or not. Can you please check this & let us know if its working?

Thanks!

**Comment by Stellyclothing** [comment]
HI @supremesupports @wildfirecreative 
Just tested the voucher system 

It was working fine if my voucher code is over the value 
For example my totally cart is $300 , my code is: $60 , 300-60 , it works fine 

BUT Here are two problems i have discovered 
1.If my cart is under the value of the voucher $45 , my code is $60 , it shows up as equal 
Which is incorrect, where on new prestashop , it allows PARTIAL USE , when i doesn't use all of my voucher, the system will regenerate a new voucher with the left over value : 
![screen shot 2015-08-16 at 11 47 55 pm](https://cloud.githubusercontent.com/assets/9522928/9293526/9a8fd9aa-4471-11e5-9c15-27f2b7860c63.png)
![screen shot 2015-08-16 at 11 48 15 pm](https://cloud.githubusercontent.com/assets/9522928/9293530/ccb92f1c-4471-11e5-90f9-53ec991818e1.png)

2.When i allow voucher to be available publicly at the checkout ( STATUS)
 , you can do that on current prestashop
It does not  show at the checkout

**Comment by supremesupports** [comment]
We are checking this issue.

**Comment by supremesupports** [comment]
Hi, I've tested both part & I think both are working.

Part - 1:
What i did is:
a) create a new voucher code for one customer (that is me) worth $100 

![v-1a](https://cloud.githubusercontent.com/assets/12905649/9323118/b4bbb8f2-459e-11e5-8ada-2ff557fc5eb0.PNG)


![v-2](https://cloud.githubusercontent.com/assets/12905649/9323104/79c0c5ee-459e-11e5-93be-2c5685548903.PNG)

![v-3a](https://cloud.githubusercontent.com/assets/12905649/9323136/e2bd85b4-459e-11e5-85d1-7a8f6ece8431.PNG)


b) After that, as a customer i bought a product worth $34.95 & applied my voucher. Then check out using free shipping. Purchased done successfully.

At front-end, I navigate to My Account >> My Voucher then i can see that i've another voucher which is $65.05. that is exactly $100 - $34.95.

![my-v1](https://cloud.githubusercontent.com/assets/12905649/9323204/d2270436-459f-11e5-98d7-e4ebddae691b.PNG)

Meanwhile, I got a mail which confirms that new voucher is created for my leftover amount:

![v-mail](https://cloud.githubusercontent.com/assets/12905649/9323226/0ed582e0-45a0-11e5-9079-96049b122b23.PNG)

If I check the back-end, the code & amount of the voucher is also updated: 

![v-1](https://cloud.githubusercontent.com/assets/12905649/9323245/44e6f5f8-45a0-11e5-894e-71836c909b92.PNG)

![v-3](https://cloud.githubusercontent.com/assets/12905649/9323247/49eeb842-45a0-11e5-8e04-5c07a62774f1.PNG)

That's the way it should work, right? Let me know if i get it wrong.

Part-2:
Please enable the following option to show voucher is available for your customer:

![v-1 - enable](https://cloud.githubusercontent.com/assets/12905649/9323350/97fce2ba-45a1-11e5-8070-2ff1f74aeaaa.PNG)

This is what i see while Highlight option is enabled:
![v-text front](https://cloud.githubusercontent.com/assets/12905649/9323368/d6f5af6a-45a1-11e5-8b3f-76003c72064d.PNG)

**Comment by Stellyclothing** [comment]
Hi Thank

**Comment by supremesupports** [comment]
Hi,
This can be done but as it's not prestashop's default feature so we need to do some custom coding. 
Perhaps you can mark this as 'Future update'.

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
I just tested again today 
And we are having trouble with the FREE SHIPPING voucher on our backend
So what happened is when we enter the free shipping voucher code on our backend , instead of giving free shipping , it took another $8 of the voucher which it shouldn't 

Thanks
Josh

**Comment by Stellyclothing** [comment]
Hi @supremesupports 
Is there a way to fix this
Theres another problem today with the voucher
First the Free Shipping code does not work

Second 
Customer got a free order without being charge for shipping
on the old CMS , no matter what customer have to pay for shipping at the checkout 
Usually if the voucher and the cart has the same value, $8.95 will be added like normal for shipping 

![screen shot 2015-09-10 at 11 43 30 pm](https://cloud.githubusercontent.com/assets/9522928/9789665/d80d53fa-5814-11e5-866d-4946e44d3a85.png)

**Comment by Stellyclothing** [comment]
@supremesupports  @wildfirecreative 

To sum up this matter
The best way to solve this vouchers problem is 

Voucher can only works others voucher codes 
& 
Free Shipping voucher code or Shipping will only work with Shipping , and shouldn't work with normal voucher code if we dont want to. Thats the old system on the CMS . now we get a lot of orders that say 0.00 ( FREE ORDER ) 

Even when we tried to create Free Shipping code on the backend, it was created as another voucher code not a shipping code 

![screen shot 2015-09-10 at 4 47 54 pm](https://cloud.githubusercontent.com/assets/9522928/9806272/05d66cce-5886-11e5-8446-ecf44cf3d691.png)

**Comment by Stellyclothing** [comment]
@supremesupports @wildfirecreative 
Can some one get on this asap 

The shipping code is not working properly 

Thanks
Josh

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
You guys are working on this ?

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi,

We are checking this now.

**Comment by Stellyclothing** [comment]
@supremesupports 
Okay let me know 

Thanks
