### ISSUE TITLE
BACKEND- ADMINISTRATION - Permission Problems - URGENT 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#40]
Hi @wildfirecreative @supremesupports  ,
The function of permission is not working at all . there are plenty of issues 

Im changing the employee permission and it seems like its not working on the back end, 
As you can see i have two browers open up 
One is mine and one is my staff , as I'm granting perimission log in and log out and refresh her browser and its not working .

I Try to allow to let them see Products on their cms but its not coming up ? i don know where to have the access to that.

Even when i decided to allow them to see orders but its not showing  either

This is really important 
Thanks
![screen shot 2015-09-04 at 12 00 46 pm](https://cloud.githubusercontent.com/assets/9522928/9675237/2c308ef0-52fe-11e5-8a5b-52ef2ecbc07f.png)

Josh

**Comment by Stellyclothing** [comment]
ALSO
@wildfirecreative @supremesupports 
Under the category background 

Missing Products & Category box in permission , i suggest you should go back and check if anything else is missing

You can see the 1.6 i opened up on youtube
![screen shot 2015-09-04 at 12 10 41 pm](https://cloud.githubusercontent.com/assets/9522928/9675213/ca7f7f0e-52fd-11e5-9392-9bd73160b936.png)

**Comment by supremesupports** [comment]
Hi,

Employee permission is working now.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
It works ,will require further testing today 
I can't close this yet 
Thanks
