### ISSUE TITLE
BACK END - EPARCEL IS NOT WORKING AGAIN

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#42]
Hi @wildfirecreative @supremesupports  ,
We can't export from CMS to Eparcel
When we exported , it showed as blank page 

Can someone fix this asap

Thanks
Josh

**Comment by supremesupports** [comment]
Hi,
This issue has been fixed.
Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
I just exported 
It has not been fixed , the columns are not correct 
Please look again

Thanks
Josh

**Comment by Stellyclothing** [comment]
Can you go back to the older version or non-production site to have a look

**Comment by supremesupports** [comment]
hi,
We copied the files from the older version. Could you please explain exactly which columns are not correct. 

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
I just tried 5 mins ago and it works, i will test it again in a sec to see if it imported properly into our eparcel system

**Comment by Stellyclothing** [comment]
It works now @supremesupports 

Thank you
