### ISSUE TITLE
Order Status

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#43]
Hi @supremesupports @wildfirecreative 

I only receive order confirmation once the payment is completed. However, when I update status to inform customer that we are progressing their order or shipping their order or refund their order, the status didn't inform customer via email. In this case, it must inform customer. Can you please fix it?

Thanks
Phong

![refund](https://cloud.githubusercontent.com/assets/9522928/9678054/740ed77e-5324-11e5-8d50-12f7f4b760d5.PNG)

**Comment by supremesupports** [comment]
Hi,

This issue has been fixed. Now, customer will be notified by e-mail if order status is changed.

Thanks.

**Comment by Stellyclothing** [comment]
I just tested , it works fine 
Thanks 
JOsh

**Comment by Stellyclothing** [comment]
Now it doesn't just tested @supremesupports 
I don't know why i was working before 

josh
