### ISSUE TITLE
Page issue when completing transaction

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#44]
Hi @supremesupports @wildfirecreative 

When I tried real credit card transaction, after click on accept payment, it took me to this page. It doesn't look right. Can you please fix it?

Thanks
Phong

![confirmationpageissues](https://cloud.githubusercontent.com/assets/9522928/9678109/f14e2d5c-5324-11e5-82f7-07eb1b6d4094.PNG)

**Comment by supremesupports** [comment]
Hi,

This issue has been fixed.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
It works now

Thanks
