### ISSUE TITLE
Missing Stelly Logo in the email

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#45]
Hi @supremesupports @wildfirecreative 

The Stelly Logo is missing when sending email to customer for order confirmation. Can you please fix it?

Thanks
Phong

![stellylogo](https://cloud.githubusercontent.com/assets/9522928/9678136/37187964-5325-11e5-8bf5-10b60f15555e.PNG)

**Comment by supremesupports** [comment]
Hi,

Logo is showing on e-mail template now. 

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
<img width="641" alt="screen shot 2015-09-06 at 11 31 48 pm" src="https://cloud.githubusercontent.com/assets/9522928/9704592/90991d9c-54ef-11e5-8d96-75a89fd2dd30.png">

Please take a look

Thanks

**Comment by Stellyclothing** [comment]
<img width="674" alt="screen shot 2015-09-06 at 11 37 10 pm" src="https://cloud.githubusercontent.com/assets/9522928/9704639/7f4d1bdc-54f0-11e5-81c1-690d63d78b6b.png">

This also

**Comment by supremesupports** [comment]
Hi,
We were doing some test in S3, may be you were testing this issue in the same time. That is why the right images where not loading. Please check this now. 

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
It works 

Thanks
