### ISSUE TITLE
We don't use Guest tracking

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#46]
Hi @supremesupports  @wildfirecreative 

We don't use guest tracking for our website? Can you please remove "Guest tracking" message from email.

Also, link to "Order history" and "My account" are not working. Can you please fix it

Thanks
Phong

![guest tracking](https://cloud.githubusercontent.com/assets/9522928/9678202/b424d3d0-5325-11e5-9a30-b5e4ce4572b2.PNG)

**Comment by supremesupports** [comment]
Hi Phong,

'Guest Tracking' has been removed. 

Thanks.

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

I just make an order by credit card and order has gone through. Just the only issues that the guest tracking is still included in the email as well as link to "order history" and "my account" is still not working.
Please have this fix.

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,

All e-mail template has been updated. Guest tracking is off, also all links should working well now.

Please have a look & let us know.

Thanks.

**Comment by supremesupports** [comment]
Hi,

Please let us know if this is working properly.

Thanks.

**Comment by Stellyclothing** [comment]
This works 

Thanks
