### ISSUE TITLE
Stock level is not shown when hover the mouse on size

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#47]
Hi @supremesupports @wildfirecreative 

I can't view stock level on each product when moving mouse to each size. It should state instock or out of stock when items sold out. Please visit stelly.com.au for information. Can you please fix it?

Thanks
Phong

![inventoryinformation](https://cloud.githubusercontent.com/assets/9522928/9678290/d847313a-5326-11e5-8fae-240015722da5.PNG)

**Comment by supremesupports** [comment]
Hi,

Product stock is showing now.

Thanks.

**Comment by Stellyclothing** [comment]
Hi

It is working now.

Thanks
Phong
