### ISSUE TITLE
Front End - Checkout does not charge for shipping ? 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#48]
Hi 
at the check out
my order was under $50 but i didn't get charge for shipping 
I have try multiple ways at the backend , it doesn't do anything 

Please have look 
![screen shot 2015-09-06 at 11 34 45 pm](https://cloud.githubusercontent.com/assets/9522928/9704610/e60adcd4-54ef-11e5-815c-6896c297f502.png)

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

We were testing payment option so we disabled Australia post carrier for a while & enabled free shipping.

Now Australia post carrier is enabled.

Thanks.
