### ISSUE TITLE
Backend- MY Paypal Transaction Id does not show up in the order 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#49]
Hi @wildfirecreative @supremesupports 
I just checked and my paypal transaction ID does not show up in my order
I have checked old orders with paypal and they have it all 

Both for credit card and paypal , in this case only my credit card order showed up but not PAPAL 

SCREEN SHOT FROM CREDIT CARD
![screen shot 2015-09-06 at 11 49 33 pm](https://cloud.githubusercontent.com/assets/9522928/9704658/4c63ca1c-54f1-11e5-92b7-c366f963c3cf.png)

**Comment by supremesupports** [comment]
Hi,
We just placed an order using PayPal where Transaction ID is not available in **Message** box BUT it's showing on **Payment** section. Please refer my screenshot:

![trac id](https://cloud.githubusercontent.com/assets/12905649/9714178/ed3523e2-5577-11e5-915b-5043f2d41a9f.PNG)

Thanks.

**Comment by Stellyclothing** [comment]
got it 

Thanks
