### ISSUE TITLE
BACKEND-SEARCH is not working

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#51]
Hi @wildfirecreative @supremesupports 
Search is not working atm
Can you have a look please 

Thanks

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Can you please fix this issue asap? Our customer can't search for product from frontend?

Thanks
Phong

**Comment by supremesupports** [comment]
Hi,
When the website had problem to load properly in the new server, we found that the search table in the database has huge amount of data and it has complex queries that effect on the website load time. That is why, our developers  disabled the search option to reduce the load . 

We are working on the admin server and load-balancers. We are hopeful to finish this by tomorrow and after that we will enable the search option again.

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
okay let us know 

Thanks
