### ISSUE TITLE
CAN WE UPLOAD TO NEW CMS ??? READY ??/

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#52]
Hey @wildfirecreative @supremesupports 

Can we start uploading on our new CMS yet ?
I Can see that a few things that i deleted on the new CMS , now it's back 
Do you guys reset them or ??

Let me know if i can do any testing like deleting products , upload new products , When we change over , will it matter ??

Thank You 
JOsh

**Comment by supremesupports** [comment]
Hi,

You can add or delete CMS pages, it won't a problem.

Also, you can do all sorts of testing regarding with products. Editing/Deleting a product on this (http://54.153.218.42/) server won't be an issue because we'll collect live site's product data tomorrow.

Thanks.
