### ISSUE TITLE
FRONT END - Can't Retrieve Password again 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#55]
Hi @wildfirecreative @supremesupports 
Just tried to re-sent the password and i don't get an email for resetting password for my online account on the front end.

Just happened now.

Thanks
Josh

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Customers are having trouble getting their password again
Can you please test and have a look again

**Comment by supremesupports** [comment]
Hi,

Are there still any issue regarding with this? Please let us know.

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
no it works fine now
