### ISSUE TITLE
BACKEND - Shipping Carrier unable to Work 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#56]
Hi @wildfirecreative @supremesupports ,
Tonight i tried to enter into carrier but it said Range Overlapping 
Also 
I just had another order coming through from USA and didn't charge her for Shipping 

I also tried to activate DHL carrier but and of course change my shipping address to usa but it didn't show up at the checkout , no matter what i tried, is there a reason why ?
<img width="967" alt="screen shot 2015-09-09 at 3 27 36 am" src="https://cloud.githubusercontent.com/assets/9522928/9742353/e8335662-56a2-11e5-811b-02d4e89c5f55.png">

Please have a look

**Comment by supremesupports** [comment]
Hi,

Shipping & Carrier option still is a bit different from Prestashop 1.4 & Prestashop 1.6. Our site is updated to v1.6 but its still holding the v1.4's carrier setting which causing the error. However, editing newly created carrier won't be a problem at all.

I recommend you not to EDIT previous carrier. Please delete previous one & create new carrier. It won't give any error. Also, if you want then we can create those carrier for you.

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
I also tried to activated DHL ones 
But at the check out , even when my address is in the states, the DHL wouldn't come up ?
Is there a reason why ? 


Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Let me test this issue in dev server.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

thank you

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
I just added another city from the states , then try to check out 
To see whether DHL would work . but it doesn't show up 

Please have a look 

Thanks 
![screen shot 2015-09-06 at 11 34 45 pm](https://cloud.githubusercontent.com/assets/9522928/9762169/0007b89e-5745-11e5-9fa6-399720586256.png)

**Comment by supremesupports** [comment]
Hi,

In our dev server, we have tested DHL & its working. Please refer my screenshot (front-end):

![dhl shipping](https://cloud.githubusercontent.com/assets/12905649/9780249/4cf03272-57a8-11e5-9123-0d3c5321c9f0.PNG)

Back-end price ranges ():

![dhl ranges](https://cloud.githubusercontent.com/assets/12905649/9780255/630cce80-57a8-11e5-888a-019603517914.PNG)


I recommend you to DELETE current DHL Express & ADD a new one (I've mention this earlier). This must work properly. 

If you still facing same problem then please send us location & price ranges (like 2nd screenshot) then we'll set up for you.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
i will test now and do it again
What about with my current shipping that wouldn't let me access
do i delete and create a new one also ?

**Comment by supremesupports** [comment]
Hi,

Yes please delete those previous one & create new. 
This will solve the issue.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports I will do that tonight after 12pm and get back to you 

right now i dont want to test on my customers 

Thanks

**Comment by supremesupports** [comment]
Hi,

Do you still facing this problem now? If, please let us know.. Otherwise you may close this issue now.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
it works 

Thanks
