### ISSUE TITLE
BACKEND- Under Customers - Under Addresses CMS - Can't change states for Staff + Customers were unable to change address

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#57]
Hi @supremesupports @wildfirecreative 
can't change States in addresses

For example go to CMS Customers - under addresses- edit addresses, 

States can't be change for my staff , i have provided permission already

Thanks
Josh

**Comment by Stellyclothing** [comment]
@wildfirecreative @supremesupports 
customers were unable to change the address too
![screen shot 2015-09-09 at 5 56 09 pm](https://cloud.githubusercontent.com/assets/9522928/9756213/bdddcf9a-571b-11e5-83d5-89f085bd2c15.png)

**Comment by supremesupports** [comment]
We checked this issue and it is working fine now.

**Comment by Stellyclothing** [comment]
Hey @supremesupports  as a staff ?? when i changed to being a staff i couldn't change it the states ?

**Comment by supremesupports** [comment]
Hi,

According to your screenshot, as a staff we've tested address part for customer which is working. We are confused about your last comment. Can you please explain a bit more or provide screenshot for this part?

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
please take a look at my screen shot 
on the left thats my account and on the right, its my staff account 
As you can see with the states, one is showing , and one is not showing , and unable to change 

![screen shot 2015-09-10 at 3 35 23 pm](https://cloud.githubusercontent.com/assets/9522928/9780854/3b934f86-57d1-11e5-9dd0-354af8e2e825.png)

**Comment by supremesupports** [comment]
Hi,

Can you please send us your staff login details so that we can check?

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

User log in
User : Caitie@stelly.com.au
Pass: stelly123

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
have you looked into this for me ?

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Give us some moments. We are checking this issue.

Thanks.

**Comment by supremesupports** [comment]
Hi,

This issue has been resolved. You'll also need to give permission to the following section (under **Location**) as well:

![permission](https://cloud.githubusercontent.com/assets/12905649/9846511/60f44282-5af4-11e5-9eed-a54f18cd4518.PNG)

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Permission is really important for us and our staffs
If you see any other errors , fix them too 

I will test this 
Thanks
