### ISSUE TITLE
FRONT & BACK END - Multiple SERVER Set up for Front End & Back 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#59]
Hi Guys @wildfirecreative  @supremesupports 
The server front & backend are having trouble loading this morning 
Can someone have a look please 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

We think server is comparatively fast now.

Thanks.

**Comment by Stellyclothing** [comment]
@supremesupports 
Waiting for the multiple servers set up 

Thanks
Josh

**Comment by wildfirecreative** [comment]
This has been addressed - can we please close this?
