### ISSUE TITLE
FRONT END - Unable to Reset password & Sender is email is Supreme

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#6]
Recieve an email from Prestashop but unable to reset my password from my email 
Sender email is from Supreme email

**Comment by supremesupports** [comment]
**Password Change Issue**
Reset password working properly (checked) but there is a problem in "Password query confirmation" email template. Change password URL link not working properly. you need to copy and paste in your browser. we will fix this issue asap.
![pass](https://cloud.githubusercontent.com/assets/12905649/9249334/b8b432fc-41e5-11e5-9629-d72f391603d8.png)

**Email Issue:**
Prestashop required Email SMTP information for sending email. Right now we are using Supreme email SMTP information for testing email service. If you provide "stelly" mail server SMTP information, we can remove supreme mail server info.

For setup we need: "Mail domain name, SMTP server, SMTP username, SMTP password, Encryption & Port number"

**Comment by Stellyclothing** [comment]
Hi

I will ask Bulletproof to provide mail server once the production site is on

Thanks
Phong

**Comment by supremesupports** [comment]
Okay, thanks

**Comment by Stellyclothing** [comment]
hey @supremesupports 
the reset and the email are working fine
But the link is not working , as i was unable to click on it 

Thanks 
josh

**Comment by supremesupports** [comment]
Hi,
Password reset link is clickable now. Please check.

Thanks!

**Comment by Stellyclothing** [comment]
okay thanks it works

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
i just tried again and this is what i had
![screen shot 2015-08-25 at 4 30 12 pm](https://cloud.githubusercontent.com/assets/9522928/9460175/ea0a7b6c-4b46-11e5-9767-d5c38cb250f2.png)

**Comment by supremesupports** [comment]
Hi, 
Just now I tried to reset password using same e-mail (joshmai@stelly.com.au) and it works. Did you receive any e-mails?

![capture](https://cloud.githubusercontent.com/assets/12905649/9484609/66b0bd5a-4bd0-11e5-8136-ca7fb2129205.PNG)

Please let us know.

Thanks!

**Comment by Stellyclothing** [comment]
Hey @supremesupports yes it works now 
Will it work overtime now ?
Thanks

**Comment by supremesupports** [comment]
It should be.

Thanks.

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

It seems working now by using gmail server. Please confirm

Thanks
Phong
