### ISSUE TITLE
BACKEND- Product Images aren't showing up 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#60]
@wildfirecreative @supremesupports 

Product images aren't showing up

**Comment by supremesupports** [comment]
Hi,

Can you please specify which images are not showing for products? If possible please send us Product ID or screenshot.

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
they are showing up now 

Thank you
