### ISSUE TITLE
FRONT END - Product Images in Product Page are squashed 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#61]
Hi @wildfirecreative @supremesupports 
the product images on the front and back are squashed when we go into product page for each product 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Additional images in Product details page are coming good now. Please have a look.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
I just checked and its still there 

Its not fixed yet 
![screen shot 2015-09-09 at 2 23 35 pm](https://cloud.githubusercontent.com/assets/9522928/9753296/f6945ab6-56fd-11e5-91fc-4021d3b99db6.png)

**Comment by supremesupports** [comment]
Hi,

We are a bit confused here.. can you please specify the exact issue? Do you mean pop-up images? Pop-up image looks good now.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
Left is normal , Right is being squeezed from the top and the bottom ? if it makes sense the dimension are the same but they both look different 

![screen shot 2015-09-09 at 4 02 00 pm](https://cloud.githubusercontent.com/assets/9522928/9754365/b9be6628-570b-11e5-8df2-e0da17a3d2b5.png)

**Comment by supremesupports** [comment]
Hi,

This issue has been fixed.

Thanks.

**Comment by Stellyclothing** [comment]
okay thanks @supremesupports

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
this image size 
take a look at the little image 

![screen shot 2015-09-10 at 4 47 40 pm 2](https://cloud.githubusercontent.com/assets/9522928/9806446/c68b5faa-5887-11e5-9fea-25ba8cf30e79.png)
came up on at the checkout

**Comment by supremesupports** [comment]
Hi,

Cart image looks good now in checkout page.

![cart-image](https://cloud.githubusercontent.com/assets/12905649/9836323/1d7f140e-5a37-11e5-9207-82aea64c06ec.PNG)

Thanks.
