### ISSUE TITLE
BACK END - Voucher is not displaying in the Order 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#62]
Hi @supremesupports @wildfirecreative 

With the latest order 134902

I found the Source, which you have mentioned before its not in the new version but it showed up anyway 

Also my voucher number does not display in the order which is a concern for us to track the vouchers
We suppose to the the VOUCHER CODE , Not voucher name 

Thanks 

Josh

**Comment by supremesupports** [comment]
Hi Josh,

Is that what you are looking for? (Collected from **Order#134902**)

![voucher](https://cloud.githubusercontent.com/assets/12905649/9754465/5de8a2ac-56eb-11e5-8bc8-86bccaeaa162.PNG)

Please let us know.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Yes thats the one but instead of the name which is really hard to look for, 
We actually need to display the code instead 

Thanks

**Comment by supremesupports** [comment]
Hi,

We believed this is the default way to show discount in Order section. If you want to see the voucher code instead then may be we need some extra work to do. 

You may consider this as **Future Update**.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Okay i will put it as future update for now 

thanks

**Comment by Stellyclothing** [comment]
@supremesupports 
Why do we have delete voucher button next to it and what does it do 
![screen shot 2015-09-11 at 10 26 58 am](https://cloud.githubusercontent.com/assets/9522928/9806340/cbd04c88-5886-11e5-921e-c233a86b3d93.png)
