### ISSUE TITLE
BACKEND - LOG IN 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#63]
Hi @wildfirecreative @supremesupports 
![screen shot 2015-09-09 at 4 59 01 pm](https://cloud.githubusercontent.com/assets/9522928/9755238/b88f1420-5713-11e5-995f-8e3ee459cd24.png)

I'm trying to log in on my CHROME and it wouldn't let me

**Comment by supremesupports** [comment]
Hi,

Can you please check this now? I think its resolved. If you are still seeing this error, please let us know which employee account you are using?

Thanks.

**Comment by Stellyclothing** [comment]
hey @supremesupports 
yes still experience it when ever i use another account of my joshmai@stelly.com.au

**Comment by supremesupports** [comment]
hi,
Profile type "Stelly Developer" had a db mismatch. It happened when the database was merged to 1.6. 
We have deleted the type "Stelly Developer". joshmai@stelly.com.au is temporarily assigned to  "In house developer".

If you need "Stelly Developer" profile type, please re-create it and and assign the necessary employees to this type. 

Thanks

**Comment by wildfirecreative** [comment]
Can this be closed now?
