### ISSUE TITLE
BACKEND - Prestashop Contanstaly Logging me out of the CMS 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#65]
hi @supremesupports 
I have to constantly log in all the time 
Can you have a look also

Thanks
Josh

**Comment by supremesupports** [comment]
please use the "Keep me logged in" option in the login box

![login](https://cloud.githubusercontent.com/assets/12905649/9806296/cd476744-5864-11e5-94fe-abcac537d156.png)

**Comment by wildfirecreative** [comment]
This is not a bug, and a solution has been provided - please close this now.
