### ISSUE TITLE
FRONT END -NEW ARRIVALS takes us to Stellyclothing.com

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#67]
Hey @wildfirecreative @supremesupports 
ON our current front page, the new arrivals button are taking us to stellyclothing.com

![screen shot 2015-09-09 at 11 33 36 pm](https://cloud.githubusercontent.com/assets/9522928/9762988/5a367012-574a-11e5-9d29-748e9cb34652.png)

**Comment by supremesupports** [comment]
Hi,

URL has been changed to stelly.com.au.

Thanks.

**Comment by Stellyclothing** [comment]
thanks it works now
