### ISSUE TITLE
FRONT END - Can't Search Products 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#68]
Hi @wildfirecreative @supremesupports 
Another bug we discovered today 
That the search on our website is not working, customers were unable to search for a product , this is what they saw .
![screen shot 2015-09-10 at 11 51 53 am](https://cloud.githubusercontent.com/assets/9522928/9778321/16fee8ca-57b2-11e5-8e57-71d09c8a1b85.png)

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
I saw your answer on our backend search, but it sounds like you meant for our front end ?

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

You guys are working on this ? 

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi,

Back end search is working now. We'll enable front end search after we implementing load balancing.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Okay great, let me know when you have enable the front end search 

Thanks
Josh

**Comment by wildfirecreative** [comment]
@supremesupports can we activate front end search now?

**Comment by Stellyclothing** [comment]
done
josh
