### ISSUE TITLE
BACK END - Customer receive an email with This is a testing Site , do not order ( URGENT)

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#69]
Hi @supremesupports @wildfirecreative 
I got a call this morning from customer 
She said she's receiving an email today saying that this is a testing email , please dont order from here 
This has happened after she has purchase, 

I thought she ordered from our testing site but she wasn't 
I managed to find out here order number which is on our live site, NOT problem but the problem was the message she receive. 

OR can you let me know how can i access to all of our messages that get send out from the CMS , i can go in there and have a look my self 

ALSO a lot of my old customers are calling today and they didn't give us the order number because of the Reference code in the order , instead of the Order Number ( ID ) . When i asked for the order number, they didn't have it, our old system didn't work with the Reference number, only had ID 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi,

We are checking this issue. Is it possible to send us the mail which client received? It'll certainly help us  to figure out the bug quickly.

Thanks.

**Comment by Stellyclothing** [comment]
@supremesupports 
Customers also saying they dont recieve confirmation email as well 

may be this problem link together 
I'm trying to get her to send me an email but she has not yet .

**Comment by Stellyclothing** [comment]
hi @supremesupports 
![screen shot 2015-09-11 at 10 18 30 am](https://cloud.githubusercontent.com/assets/9522928/9805445/4dd5a814-587c-11e5-9a00-bb854b139868.png)

you guys still have the message at the check out on our Stelly.com.au website. 
Please check on all section to make sure this message does not come up again 


Thanks

**Comment by supremesupports** [comment]
Hi,
This is fixed. 
Thanks

**Comment by Stellyclothing** [comment]
okay thanks
