### ISSUE TITLE
FRONT END - EMAIL - Payment accepted today , didn't get an email 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#71]
Hi today 
I tested another order 135134 on new CMS
i didn't get payment accepted email
I changed to shipped and i received an email that it said my item has been shipped

Please fix this asap 

![screen shot 2015-09-11 at 10 26 58 am](https://cloud.githubusercontent.com/assets/9522928/9806477/2a760eb6-5888-11e5-88ed-8fdc44a78916.png)

thanks
Josh

**Comment by supremesupports** [comment]
Hi,
Some emails are going to spam folder and some are delivered very late. We need take care of the the email system and we need bulletproof's help for that because this is a server issue. 

Thanks

**Comment by Stellyclothing** [comment]
@supremesupports thanks ill follow up with Phong & Bulletproof

**Comment by Stellyclothing** [comment]
it works now @supremesupports 

thanks
josh
