### ISSUE TITLE
BACKEND - BANKWIRE PAYMENT need to be changed to PAYPAL or Credit Card

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#72]
Hi @supremesupports 
There are a few orders on the new CMS , it has Bankwire payment ( bank deposit ) 
When on our website we dont offer banker payment , 
Some orders falled under this payment method 

134946
134948
134951
134954
134955
134958
134960
134961
134965
135017
135018
135023

If they fall under paypal or credit card payment, please check the payment method  to avoid confusion from out end

**Comment by supremesupports** [comment]
Hi,

Payment's option has been updated according to old site.

Thanks,.

**Comment by Stellyclothing** [comment]
Hi @supremesupports 
These orders also need to be changed payment status to avoid confusion from my accounting team 

Please change them 
![screen shot 2015-09-13 at 11 16 57 pm](https://cloud.githubusercontent.com/assets/9522928/9836864/f8a70246-5a6c-11e5-8de4-54b015a8ee12.png)


thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

All those orders has been updated.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
It works now, all good thanks

**Comment by Stellyclothing** [comment]
hey @supremesupports 
this came across today 
Customer received an email from our system ?

Stelly
 
Hi,
 
Error reporting from your PayPalAPI module
 
A client has encountered a problem with the module PayPalAPI, see the report:
 
PayPal response:
-> 
Making new connection to 'api-3t.paypal.com/nvp'
Connect with CURL method successful
Sending this params:
METHOD=SetExpressCheckout&VERSION=106&PWD=*********&USER=kroooutfitters_api1.gmail.com&SIGNATURE=*********&CANCELURL=http%3A%2F%2Fstelly.com.au%2Forder%3Fpaypal_ec_canceled%3D1%26&RETURNURL=http%3A%2F%2Fstelly.com.au%2Fmodules%2Fpaypal%2Fexpress_checkout%2Fpayment.php&NOSHIPPING=1&BUTTONSOURCE=PRESTASHOP_EC&L_PAYMENTREQUEST_0_NUMBER0=18561&L_PAYMENTREQUEST_0_NAME0=Keep+It+Simple+Ribbed+Bodycon+Dress+-+Latte+-+SHOP+BY+SIZES+%3A+8&L_PAYMENTREQUEST_0_DESC0=When+in+doubt+this+dress+will+save+you%21+It+feature...&L_PAYMENTREQUEST_0_AMT0=45&L_PAYMENTREQUEST_0_QTY0=1&PAYMENTREQUEST_0_PAYMENTACTION=Sale&PAYMENTREQUEST_0_CURRENCYCODE=AUD&PAYMENTREQUEST_0_SHIPPINGAMT=8.95&PAYMENTREQUEST_0_ITEMAMT=45&PAYMENTREQUEST_0_AMT=53.95&ADDROVERRIDE=1&EMAIL=brooke.ellen87%40hotmail.com&PAYMENTREQUEST_0_SHIPTONAME=Brooke+Stephens&PAYMENTREQUEST_0_SHIPTOPHONENUM=0422627599&PAYMENTREQUEST_0_SHIPTOSTREET=4%2F13+Indy+Court&PAYMENTREQUEST_0_SHIPTOSTREET2=&PAYMENTREQUEST_0_SHIPTOCITY=Nerang&PAYMENTREQUEST_0_S HIPTOSTATE=QLD&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=AU&PAYMENTREQUEST_0_SHIPTOZIP=4211&SOLUTIONTYPE=Sole&LANDINGPAGE=Login&USER=kroooutfitters_api1.gmail.com&PWD=*********&SIGNATURE=*********
Send with CURL method failed ! Error: Unknown SSL protocol error in connection to api-3t.paypal.com:443 
Connect failed with fsockopen method
 
Stelly powered with PrestaShop™
stelly-logo-1432444071.jpg
