### ISSUE TITLE
BACKEND & FRONT END 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#73]
A lot of our products again have two different product combination
If you look at these two products 
The combination are completely different  

I assume the back end and category page are the same, but on the product page ( display multiple products ) are incorrect

![60e021d65d470bbaeecd5b7c651820760e877769c961f80f25f573f0c893f665](https://cloud.githubusercontent.com/assets/9522928/9807932/59d23c2e-589d-11e5-9cc8-e754a6fd01ad.jpg)
![e17f10b5b20a6ad9ca2eaa9d716a0f7e2a9e104ade9ecd517a90ec9f9967dfe5](https://cloud.githubusercontent.com/assets/9522928/9807933/5a20a71a-589d-11e5-9738-72738e20a3b2.jpg)

**Comment by supremesupports** [comment]
Hi,

I just grabbed screenshot for the same product (ID#17210) & I see that the quantity is showing same in both category & product page.

![quantity-category](https://cloud.githubusercontent.com/assets/12905649/9836010/7c933db6-5a29-11e5-9e00-fa473ec8d734.PNG)

![quantity-product](https://cloud.githubusercontent.com/assets/12905649/9836012/8659c05e-5a29-11e5-9cf4-2bcdcc22c60e.PNG)

Can you please check now if this is still happening.

Thanks.

**Comment by Stellyclothing** [comment]
Hi Supremesupports,

It is working fine after clearing the caches.

Thanks
Phong
