### ISSUE TITLE
Urgent Retrieve password not sending email

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#74]
Hi @supremesupports @wildfirecreative 

When I retrieve password, it said a confirmation e-mail has been sent to your address but email not sending. Can anyone take a look at this issues and have it fix?

Kindly regards
Phong

**Comment by supremesupports** [comment]
Hi,
The email functionality is not working properly. Sometime  the emails are going to spam and some time  mail is delivered very late. We think  smtp should be used instead of normal php mail function with localhost:25.

Thanks

**Comment by Stellyclothing** [comment]
Hi Supremesuports,

Yes I think so. I changed it to admin@stelly.com.au for now. It seems working fine.

Thanks
Phong

**Comment by Stellyclothing** [comment]
it works fine now
