### ISSUE TITLE
FRONT END - Category Page ( left hand side ) is missing & category image is not working

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#75]
HI @wildfirecreative @supremesupports 

When i got clothes - then dresses - all the left hand side categories went missing , they suppose to be there with other category as well 

also theres another bug we found , missing category banner image 
![Uploading Screen Shot 2015-09-14 at 12.42.34 am.png…]()
![Uploading Screen Shot 2015-09-14 at 12.43.37 am.png…]()

**Comment by supremesupports** [comment]
Hi,

I can't see your screenshots.

If you enter to a sub-category then you will see child categories of that specific sub-category. Like, Dress has following child categories which are showing now:

![sub-category](https://cloud.githubusercontent.com/assets/12905649/9843068/834b5058-5ad8-11e5-89d8-3c218455c661.PNG)

For the banner, did you upload any banner for this specific Dress category? If not then you will need to upload one to show it under this category.

Thanks.
