### ISSUE TITLE
FRONT END- Unable to request for Restock

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#8]
Hi , 
On our current site, every product when the product size turns Grey , which means its out of stock 
Customer can select on it and enter their emails when we restock the product. 

we can not do that on our new website . 

Thanks

![screen shot 2015-08-13 at 2 47 52 pm](https://cloud.githubusercontent.com/assets/9522928/9242736/f328786a-41c9-11e5-9d66-0bd06494d4d0.png)

**Comment by supremesupports** [comment]
Hi,
Request of restock is working. Please have a look now.

Thanks.

**Comment by Stellyclothing** [comment]
Hi

Thanks. Working now

Thanks
Phong

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative i tried to select on the Grey size ( out of stock ) but it wont ask for my email to notify me when to restock , it has not been fixed. Please check again . Thank you

**Comment by supremesupports** [comment]
Hi, I've checked this & i saw that this product has available quantity for all sizes. May be that why you are not seeing that notify field? Probably a cache issue in your browser?

![quantity](https://cloud.githubusercontent.com/assets/12905649/9293888/230ee6d2-445d-11e5-8869-29afaf38ba15.PNG)

Check this product anyway: http://54.153.131.0/just-in/18141-cutout-bodycon-dress-white-floral.html

Thanks!

**Comment by Stellyclothing** [comment]
yup it works now !!! thank you 
But does it actually will send me an email once i restock the product ? @wildfirecreative @supremesupports . I'm unable to check because when i tried to search a product, the CMS goes blank !!

**Comment by supremesupports** [comment]
Hi,
I've tested this part using product ID: 18143. After restock, as a customer I've got  an alert in My Account >> My Alerts

![restock](https://cloud.githubusercontent.com/assets/12905649/9349105/a5549892-4662-11e5-966e-186d67e746b3.PNG)

Thanks!

**Comment by Stellyclothing** [comment]
Thank you

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 

I just tested 
What happened is , after you log in 
there are size 6 & 12 that are not available 

if you click size 6 , the notify button is there, but if you click size 12 it doesn't show up 
If you log on then it works for both 
You can come back to it when you have time


Thank You
Josh

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Without sign in, request stock is working on all internet explore. However, When I sign in, request stock is not working on IE but  working on safari, Google Chrome, Mozilla Firefox. 

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,

Request for restock in IE11 is working now.

Thanks!

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Thank you. It is working now

Thanks
Phong
