### ISSUE TITLE
BACKEND - Google Analytics Needs to be Fixed ( On All Pages )

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#80]
Hi @wildfirecreative @supremesupports 

I called up google today and they discovered all the code are implemented at the wrong area on my website ( THIS IS ON ALL PAGES ) 
First if haven't , please download Google Tag Assistant on Chrome, it will assist you on whether where you have placed the tag were correct or incorrect .

This is what i saw and i also got google to check on every page and they all seemed to be in the wrong place.

![screen shot 2015-09-16 at 12 25 14 pm](https://cloud.githubusercontent.com/assets/9522928/9894967/57ac3ad4-5c6d-11e5-83ce-431ff15d813f.png)

HERE IS thE CODE AGAIN : 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35324655-1', 'auto');
  ga('send', 'pageview');

</script>
Since the code doesn't show up on here , i will send an email 

Attached in the interaction from GOOGLE Analytics 
![screen shot 2015-09-16 at 12 22 31 pm](https://cloud.githubusercontent.com/assets/9522928/9894987/8a3e4884-5c6d-11e5-8c98-ce3806f71ef6.png)
 

Thanks
josh

**Comment by Stellyclothing** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35324655-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by supremesupports** [comment]
Hi Josh,

We guess this is fixed now. Please check.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

So you have embedded on all pages on Stelly website 
is there any pages you guys didn't ? 

Thanks 
Josh

**Comment by supremesupports** [comment]
Hi,

Its embedded to <head> tag according to Google's suggestion. So, it should be appear in all pages.

Thanks.

**Comment by wildfirecreative** [comment]
Can this now be closed?
