### ISSUE TITLE
BACK END - GOOGLE ADWORDS Tracking code is Incorrect 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#81]
Hi @wildfirecreative @supremesupports 

The current tracking code for Adwords is placing on the Home Page of Stelly.com.au Which is incorrect

The code needs to be place one at the checkout for 

Thank you page for Credit Card
http://stelly.com.au/modules/securepayxml/process.php
![screen shot 2015-09-16 at 12 42 43 pm](https://cloud.githubusercontent.com/assets/9522928/9895149/8cda6b16-5c6f-11e5-8c33-2aa435d46e04.png)

Thank You Page for Paypal :
http://stelly.com.au/module/paypal/submit?key=2185b00059a3f98c9b987e3313350750&id_module=134&id_cart=3542&id_order=135705
![screen shot 2015-09-16 at 12 42 35 pm](https://cloud.githubusercontent.com/assets/9522928/9895153/97b10356-5c6f-11e5-9b06-8228a5655360.png)

I will send email again with the intructionw with GOOGLE adwords

**Comment by supremesupports** [comment]
Hi,

Google adwords code has been added to Securepay & Paypal payment confirmation pages. Its removed from other pages.

Please check now & let us know.

Thanks.

**Comment by Stellyclothing** [comment]
@supremesupports 
Thank you , i will double check with the google team 
I shall wait 1 week to check all the data to come through.

Thanks
Josh

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Sorry about this
But theres a mistake i just made 

With my email , that was for Credit Card


I will send another paypal email over shortly -

**Comment by Stellyclothing** [comment]
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 996221430;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "IJP2CNqh7V8Q9sOE2wM";
var google_conversion_value = 1.00;
var google_conversion_currency = "AUD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/996221430/?value=1.00&amp;currency_code=AUD&amp;label=IJP2CNqh7V8Q9sOE2wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by supremesupports** [comment]
Hi,

New code has been placed for Paypal. Please check if both are working properly. 

Thanks.

**Comment by Stellyclothing** [comment]
@supremesupports 
thank you

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

I just talked to google again today 

with Paypal page : you will need to place the code just before the Closing <body> tag
![screen shot 2015-09-18 at 11 20 54 am](https://cloud.githubusercontent.com/assets/9522928/9949880/09fc23d6-5df7-11e5-84fa-2ee73ee4f42b.png)

With credit card : the code line is not in there , please put them just before the closing <body> tag as well.

Thanks 
josh

**Comment by Stellyclothing** [comment]
https://support.google.com/adwords/answer/6095821?hl=en-AU&vid=1-635781351707938682-3770185377

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Can you guys add the tracking code for my adwords Credit card account 
i just checked today and it has not been added 
Thank You
Josh

**Comment by wildfirecreative** [comment]
@supremesupports have you actioned the above yet?

**Comment by Stellyclothing** [comment]
@supremesupports @wildfirecreative 
This has not been done


Thanks
JOsh

**Comment by wildfirecreative** [comment]
@supremesupports can you please review whether the code has been added to the page after CC payment? Josh believes it has not yet been added

**Comment by Stellyclothing** [comment]
@wildfirecreative luke 
This has not been done yet 

Can someone get on top of this asap 
It has been too long 

Also i dont want to create another issue
But when you guys changed cloud front, 
this also happened , bottom banner is missing 
![screen shot 2015-10-26 at 11 24 09 am](https://cloud.githubusercontent.com/assets/9522928/10719018/c68a7800-7bd3-11e5-9cd2-2879b524326b.png)

**Comment by wildfirecreative** [comment]
Hi Josh,

RE the tracking code see a question from Supreme below -

*"We are using the google_conversion_id = 996221430 as the tracking ID for
both the payment confirmation page? I am guessing that they have a
different one for these 2 pages or something?*



*Can you plz ask them to send the codes again for both these payment pages
so we can compare the conversion ID ---if it is right one or not?"*

Cheers,

Luke

<http://wildfirecreative.com.au>

**Comment by supremesupports** [comment]
Hi,
GOOGLE ADWORDS Tracking code was added long time ago, but this post was not replied as a mistake. 

We are using google_conversion_id = 996221430 in paypal and credit card payment success pages . Please ensure that this is the right google_conversion_id. 

The banner issue is fixed too. 

Thanks
Raju
Programmer, Supreme Support

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
like i have said before its the same one but need to be added on both pages
on Paypal page : http://stelly.com.au/module/paypal/submit?key=2185b00059a3f98c9b987e3313350750&id_module=134&id_cart=3542&id_order=135705

Which you have added tracking code from google 

But on credit card page : http://stelly.com.au/modules/securepayxml/process.php
You didn't add the tracking code : i have tried to search for the source code, but i wasn't able to find  

Josh 
![screen shot 2015-10-26 at 1 37 45 pm](https://cloud.githubusercontent.com/assets/9522928/10720013/8411e130-7be6-11e5-9f08-0fcb60c292e8.png)

**Comment by supremesupports** [comment]
Hi,
Credit card success page code will be different when it is a real transaction. You can not get that scenario if you directly visit http://stelly.com.au/modules/securepayxml/process.php, this url will return a success message plus GOOGLE ADWORDS Tracking code  when you go to that page after a real transaction. 

Please check the page placing a real order and you can also check your google adwords account   records. If the code is not working properly then you will not get any records of credit cart translation page. 
Thanks

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

I have checked over and over again
This is where i want you to put the adwords conversion code 
I have my Facebook conversion tracking code there and its working 


Thanks
Josh

**Comment by wildfirecreative** [comment]
Did you follow the instructions provided and make a transaction then check?

Cheers,

Luke

<http://wildfirecreative.com.au>

**Comment by Stellyclothing** [comment]
@supremesupports @wildfirecreative 
This is the page after my checkout for credit card,

**Comment by Stellyclothing** [comment]
hey @supremesupports @wildfirecreative 
It works

Thanks
