### ISSUE TITLE
FRONT END - CHECKOUT + quantity button at the checkout 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#84]
Hi @supremesupports @wildfirecreative 
Like we have discussed earlier at the meeting the other day 
This is also a problem, i think in regarding about the javascript ?
![screen shot 2015-09-18 at 3 37 05 pm](https://cloud.githubusercontent.com/assets/9522928/9952582/d8fd845e-5e1a-11e5-8d0b-c7c3fc3052ae.png)

When pressing + to add quantity of the product, it doesn't work or rather lagging ? 
Thanks
Josh

**Comment by supremesupports** [comment]
Hi,
This issue has been fixed. After the + - is clicked, sometime you need to wait to finish the ajax call.  
Thanks

**Comment by wildfirecreative** [comment]
Can this now be closed?
