### ISSUE TITLE
BACKEND - Product images not showing up on All Orders

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#9]
HI ,

All product images are not showing up on all orders 

Phong

**Comment by supremesupports** [comment]
Hello,
We've checked around 25-30 orders but we couldn't found one where product image is missing.
Can you please send us an order ID where product image is not coming up? You can also attach a screenshot to address this issue in a more understandable way.

Thanks.

**Comment by Stellyclothing** [comment]
Hi

Thanks. I can see images now.

Thanks
Phong
