### ISSUE TITLE
URGENT - ERRORS ON ALL PAGES

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#90]
HI @supremesupports @wildfirecreative 

Please see the attachment for details. Errors are on all pages. Can anyone take a look at the issues urgent?

![frontpageissues](https://cloud.githubusercontent.com/assets/9522928/10151754/31dd30b2-668e-11e5-9d16-961ade21b7ed.PNG)
![frontpageissues](https://cloud.githubusercontent.com/assets/9522928/10151759/39d08e2c-668e-11e5-8cdf-06caddd84c45.PNG)
![newarival](https://cloud.githubusercontent.com/assets/9522928/10151761/43b6e09e-668e-11e5-91b6-44680bbad29a.PNG)

Thanks
Phong

**Comment by supremesupports** [comment]
Hi,
This problem at app-02 has been fixed.
thanks

**Comment by Stellyclothing** [comment]
Hi @supremesupports 

Thank you

Thanks
Phong
