### ISSUE TITLE
Checkout BUG ???

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#91]
![screen shot 2015-09-27 at 11 22 49 am](https://cloud.githubusercontent.com/assets/9522928/10155281/8a0eca98-66b6-11e5-9a9e-d7737f316c9e.png)

??? Shipping option on the back end is fine but this is what it has shown ?
@wildfirecreative @supremesupports

**Comment by bahalulkabir** [comment]
![order-stelly](https://cloud.githubusercontent.com/assets/133858/10183847/4b379804-6756-11e5-89f7-3b917132d8c2.png)

Shipping option issue fixed, can you please check from your side and let us know.

Thanks

**Comment by supremesupports** [comment]
![order-stelly](https://cloud.githubusercontent.com/assets/12905649/10184509/1b03a0c0-675f-11e5-9efb-f6e30af59a34.png)

We don’t see this happening. can you please check from your side and let us know.

Thanks
